version: 2
jobs:
  build:
    docker:
      - image: circleci/python

    working_directory: /app

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/next-prod.tar

      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/next-prod.tar | true

      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=next-prod -t next-prod -f Dockerfile.dev .

      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/next-prod.tar next-prod

      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/next-prod.tar

      - run:
          name: Run tests
          command: |
            docker run --name next-prod-container next-prod /bin/bash -c "yarn test"

      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            pip install --no-cache-dir awsebcli

      - run:
          name: Deploying
          command: eb deploy Dockernextcircleci

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
